name: flutter_angle_windows
description: "Flutters Almost Native Graphics Layer Engine for windows."
version: 0.0.1
homepage: https://github.com/Knightro63/flutter_angle/tree/main/flutter_angle_windows

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: flutter_angle
    platforms:
      windows:
        pluginClass: FlutterAnglePlugin

