name: flutter_angle_example
description: Demonstrates how to use the flutter_angle plugin.
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_angle:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_angle_darwin:
    path: ../../flutter_angle_darwin

flutter:
  uses-material-design: true
  assets:
    - assets/ 
