name: flutter_angle_darwin
description: "Flutters Almost Native Graphics Layer Engine for ios and osx."
version: 0.1.0
homepage: https://github.com/Knightro63/flutter_angle/tree/main/flutter_angle_darwin

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: flutter_angle
    platforms:
      ios:
        pluginClass: FlutterAnglePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterAnglePlugin
        sharedDarwinSource: true

